{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Aula 19 -Tratamento de exceções\n",
    "<div class=\"alert alert-block alert-success\">\n",
    "    <b>Capítulo 16 do livro: </b> \n",
    "    <p>DEITEL, Harvey M.; DEITEL, Paul J. C++: como programar. 5.ed. São Paulo: Prentice Hall, 2006.\n",
    "</div>\n",
    "\n",
    "## OBJETIVOS\n",
    "Nesta aula, você aprenderá:\n",
    "- O que são exceções e quando utilizá-las.\n",
    "- A utilizar **try, catch** e **throw** para detectar, indicar e tratar exceções, respectivamente.\n",
    "- A processar exceções não interceptadas e inesperadas.\n",
    "- Como declarar novas classes de exceção.\n",
    "- Como o desempilhamento permite que exceções não capturadas em um escopo sejam capturadas em outro escopo.\n",
    "- A tratar falhas **new**.\n",
    "- Como utilizar **auto_ptr** para evitar vazamentos de memória.\n",
    "- A entender a hierarquia de exceções-padrão.\n",
    "\n",
    "## 1 Introdução\n",
    "- Exceções\n",
    "    - Indicam os problemas que ocorrem durante a execução de um programa.\n",
    "    - Ocorrem raramente.\n",
    "- Tratamento de exceções\n",
    "    - Pode solucionar exceções\n",
    "        - Permite que um programa continue a executar ou\n",
    "        - Notifica o usuário sobre o problema e\n",
    "        - Encerra o programa de uma maneira controlada.\n",
    "    - Torna os programas robustos e tolerantes a falhas.\n",
    "\n",
    "## Dica de prevenção de erro 1\n",
    "- O tratamento de exceções ajuda a aprimorar a tolerância a falhas de um programa.\n",
    "\n",
    "## Observação de engenharia de software 1\n",
    "- O tratamento de exceções fornece um mecanismo-padrão para processar erros. Isso é especialmente importante ao trabalhar em um projeto com uma grande equipe de programadores.\n",
    "\n",
    "## 2 Visão geral do tratamento de exceções\n",
    "- Misturando programa e lógica de tratamento de erros\n",
    "    - Exemplo de pseudocódigo\n",
    "        - Execute uma tarefa\n",
    "        - Se a tarefa precedente não tiver sido executada corretamente\n",
    "            Realize processamento de erro\n",
    "        - Execute a tarefa seguinte\n",
    "        - Se a tarefa precedente não tiver sido executada corretamente\n",
    "            - Realize processamento de erro\n",
    "        - …\n",
    "- Torna o programa difícil de ler, modificar, manter e depurar.\n",
    "\n",
    "## Dica de desempenho 1\n",
    "- Se problemas em potencial ocorrem raramente, misturar a lógica do programa e a lógica do tratamento de erro pode diminuir seu desempenho, \n",
    "- porque o programa tem de realizar testes (possivelmente freqüentes) para determinar se a tarefa foi executada corretamente e se a próxima tarefa pode ser realizada.\n",
    "\n",
    "## 2 Visão geral do tratamento de exceções (cont.)\n",
    "- Tratamento de exceções\n",
    "    - Remove código de tratamento de erros da ‘linha principal’ de execução do programa.\n",
    "    - Os programadores podem tratar qualquer exceção que quiserem.\n",
    "        - Todas as exceções,\n",
    "        - Todas as exceções de um determinado tipo ou\n",
    "        - Todas as exceções de um grupo de tipos relacionados.\n",
    "\n",
    "## 3 Exemplo: tratando uma tentativa de divisão por zero\n",
    "- Classe exception\n",
    "    - É a classe básica padrão do C++ para todas as exceções.\n",
    "    - Fornece às suas classes derivadas a função **virtual what**.\n",
    "        - Retorna a mensagem de erro armazenada da exceção.\n",
    "- Observe a classe DivideByZeroException [DivideByZeroException.h](src/ch16/Fig16_01_02/DivideByZeroException.h)\n",
    "\n",
    "\n",
    "## 3 Exemplo: tratando uma tentativa de divisão por zero (cont.)\n",
    "- Blocos try\n",
    "    - A palavra-chave try é seguida por chaves ({}).\n",
    "    - Deve encerrar\n",
    "        - Instruções que possam provocar exceções e\n",
    "        - Instruções que devem ser puladas no caso de uma exceção.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Observação de engenharia de software 2\n",
    "- As exceções podem emergir pelo código explicitamente mencionado em um bloco try, \n",
    "    - por meio de chamadas a outras funções e \n",
    "    - por meio de chamadas de função profundamente aninhadas, iniciadas pelo código em um bloco try.\n",
    "\n",
    "## 3 Exemplo: tratando uma tentativa de divisão por zero (cont.)\n",
    "- Handlers catch\n",
    "    - Seguem imediatamente um bloco try.\n",
    "        - Um ou mais handlers catch para cada bloco try.\n",
    "    - Palavra-chave catch.\n",
    "    - Parâmetro de exceção encerrado entre parênteses\n",
    "        - Representa o tipo de exceção a ser processado.\n",
    "        - Pode oferecer um nome de parâmetro opcional para interagir com o objeto de exceção capturado.\n",
    "    - Executa se o tipo de parâmetro de exceção corresponder à exceção lançada no bloco try.\n",
    "        - Poderia ser uma classe básica da classe da exceção lançada.\n",
    "        \n",
    "        \n",
    "## Rode o programa Fig16_02() no terminal\n",
    "- Observe o seu código fonte [Fig16_02.cpp](src/ch16/Fig16_01_02/Fig16_02.cpp).\n",
    "    - Abra um novo terminal através do menu File > New > Terminal\n",
    "    - Digite: cling src/ch16/Fig16_01_02/Fig16_02.cpp\n",
    "    - Aperte Enter e entre com valores para o numerador e denominador."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Erro comum de programação 1\n",
    "- É um erro de sintaxe colocar código entre um bloco try e seus blocos catch correspondentes.\n",
    "\n",
    "## Erro comum de programação 2\n",
    "- Cada handler catch pode ter um único parâmetro\n",
    "    - especificar uma lista de parâmetros de exceção separados por vírgulas é um erro de sintaxe.\n",
    "\n",
    "## Erro comum de programação 3\n",
    "- É um erro de lógica capturar o mesmo tipo em dois handlers catch diferentes que se seguem a um único bloco try.\n",
    "\n",
    "## 3 Exemplo: tratando uma tentativa de divisão por zero (cont.)\n",
    "- Modelo de terminação do tratamento de exceções\n",
    "    - O bloco try expira quando ocorre uma exceção.\n",
    "        - As variáveis locais no bloco try saem do escopo.\n",
    "    - O código dentro do handler catch correspondente executa.\n",
    "    - O controle é retomado com a primeira instrução após o último handler catch subseqüente ao bloco try.\n",
    "        - O controle não retorna ao ponto em que a exceção ocorreu.\n",
    "- Desempilhamento\n",
    "    - Ocorre se nenhum handler catch correspondente for encontrado.\n",
    "    - O programa tenta localizar outro bloco try envolvente na função chamadora.\n",
    "\n",
    "## Erro comum de programação 4\n",
    "- Erros de lógica podem ocorrer se você assumir que, depois que uma exceção for tratada, o controle retornará à primeira instrução depois do ponto de lançamento.\n",
    "\n",
    "## Dica de prevenção de erro 2\n",
    "- Com o tratamento de exceções, um programa pode continuar executando (em vez de encerrar) depois de lidar com um problema. \n",
    "- Isso ajuda a assegurar um tipo de aplicativo robusto que colabora para o que é chamado de computação de missão crítica.\n",
    "\n",
    "## 3 Exemplo: tratando uma tentativa de divisão por zero (cont.)\n",
    "- Lançando uma exceção\n",
    "    - Use a palavra-chave throw seguida de um operando que represente o tipo de exceção.\n",
    "        - O operando throw pode ser de qualquer tipo.\n",
    "            - Se o operando throw for um objeto, é chamado de objeto de exceção.\n",
    "    - O operando throw inicializa o parâmetro de exceção no handler catch correspondente, se encontrar algum.\n",
    "\n",
    "## Dica de desempenho 2\n",
    "- Capturar um objeto de exceção por referência elimina o overhead de copiar o objeto que representa a exceção lançada.\n",
    "\n",
    "## Boa prática de programação 1\n",
    "- Associar cada tipo de erro de tempo de execução com um objeto de exceção adequadamente nomeado aumenta a clareza do programa.\n",
    "\n",
    "## 4 Quando utilizar o tratamento de exceções\n",
    "- Quando usar o tratamento de exceções\n",
    "    - Para processar erros síncronos\n",
    "        - Que ocorrem quando uma instrução é executada.\n",
    "    - Não para processar erros assíncronos\n",
    "        - Que ocorrem paralelamente à e independentemente da execução do programa.\n",
    "    - Para processar problemas em elementos predefinidos do software.\n",
    "        - Como funções e classes predefinidas.\n",
    "        - O tratamento de erros pode ser executado pelo código do programa a ser personalizado com base nas necessidades do aplicativo.\n",
    "\n",
    "## Observação de engenharia de software 3\n",
    "- Incorpore sua estratégia de tratamento de exceções no sistema desde o princípio do processo de projeto. \n",
    "- Pode ser difícil incluir um tratamento de exceções eficiente depois que um sistema já foi implementado.\n",
    "\n",
    "## Observação de engenharia de software 4\n",
    "- O tratamento de exceções fornece uma técnica única e uniforme para processamento de problemas. \n",
    "- Isso ajuda os programadores em grandes projetos a entender o código de processamento de erro uns dos outros.\n",
    "\n",
    "## Observação de engenharia de software 5\n",
    "- Evite utilizar o tratamento de exceções como uma forma alternativa de fluxo de controle. \n",
    "- Essas exceções ‘adicionais’ podem ‘entrar no caminho’ de verdadeiras exceções do tipo erro.\n",
    "\n",
    "## Observação de engenharia de software 6\n",
    "- O tratamento de exceções simplifica a combinação de componentes de software e permite trabalhar em conjunto eficientemente, \n",
    "    - possibilitando que os componentes predefinidos comuniquem problemas para componentes específicos ao aplicativo, \n",
    "    - que então podem processar os problemas de maneira específica ao aplicativo.\n",
    "\n",
    "## Dica de desempenho 3\n",
    "- Quando não ocorrer nenhuma exceção, o código de tratamento de exceções não provoca ou provoca poucos prejuízos no desempenho. \n",
    "- Portanto, os programas que implementam o tratamento de exceções operam com mais eficiência do que os programas que mesclam o código de tratamento de erros com a lógica do programa.\n",
    "\n",
    "## Observação de engenharia de software 7\n",
    "- As funções com condições de erro comuns devem retornar 0 ou NULL (ou outros valores adequados) em vez de lançar exceções. \n",
    "- Um programa que chama tal função pode verificar o valor de retorno para determinar o sucesso ou falha da chamada de função.\n",
    "\n",
    "## 5 Relançando uma exceção\n",
    "- Relançando uma exceção\n",
    "    - Instrução throw; vazia.\n",
    "    - Usada quando um handler catch não pode ou só pode processar parcialmente uma exceção.\n",
    "    - O próximo bloco try envolvente tenta corresponder à exceção com um de seus handlers catch.\n",
    "- Rode o programa **Fig16_03()** abaixo e observe o seu código fonte [Fig16_03.cpp](src/ch16/Fig16_03/Fig16_03.cpp)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "main invokes function throwException\n",
      "  Function throwException throws an exception\n",
      "  Exception handled in function throwException\n",
      "  Function throwException rethrows exception\n",
      "\n",
      "Exception handled in main\n",
      "Program control continues after catch in main\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "// Fig. 16.3: Fig16_03.cpp\n",
    "// Demonstrando o relançamento de exceção.\n",
    "#include \"src/ch16/Fig16_03/Fig16_03.cpp\"\n",
    "\n",
    "Fig16_03()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Erro comum de programação 6\n",
    "- Executar uma instrução throw vazia situada fora de um handler catch produz uma chamada à função terminate, \n",
    "    - que abandona o processamento de exceção e termina o programa imediatamente.\n",
    "\n",
    "## 6 Especificações de exceção\n",
    "- Especificações de exceção  (listas também conhecidas como throw)\n",
    "    - Palavra-chave throw\n",
    "    - Lista separada por vírgulas de classes de exceção entre parênteses\n",
    "    - Exemplo\n",
    "        - int someFunction( double value )\n",
    "            <br>throw ( ExceptionA, ExceptionB, ExceptionC ) {}\n",
    "        - Indica que someFunction pode lançar exceções dos tipos ExceptionA, ExceptionB e ExceptionC.\n",
    "\n",
    "## 6 Especificações de exceção (cont.)\n",
    "- Especificações de exceção (cont.)\n",
    "    - Uma função pode throw (lançar) exceções somente dos tipos em sua especificação ou de tipos derivados desses tipos.\n",
    "        - Se uma função lançar uma exceção que não pertença ao tipo especificado, a função unexpected será chamada.\n",
    "            - Isso normalmente encerra o programa.\n",
    "    - Se não houver nenhuma especificação, isso quer dizer que a função pode lançar qualquer exceção.\n",
    "    - Uma especificação de exceção vazia, throw(), indica que a função não pode lançar nenhuma exceção.\n",
    "\n",
    "## Erro comum de programação 7\n",
    "- Lançar uma exceção que não foi declarada em uma especificação de exceção da função produz uma chamada à função unexpected.\n",
    "\n",
    "## Dica de prevenção de erro 3\n",
    "- O compilador não gerará um erro de compilação se uma função contiver uma expressão throw para uma exceção não listada na especificação de exceção da função. \n",
    "- Só ocorrerá erro quando essa função tentar lançar essa exceção em tempo de execução. \n",
    "- Para evitar surpresas em tempo de execução, verifique cuidadosamente seu código para que as funções não lancem exceções não listadas em suas especificações de exceção.\n",
    "\n",
    "## 7 Processando exceções inesperadas\n",
    "- Função unexpected\n",
    "    - É chamada quando uma função lança uma exceção que não se encontra em sua especificação de exceção.\n",
    "    - Chama a função registrada com a função set_unexpected.\n",
    "    - A função terminate é chamada por padrão.\n",
    "- Função set_unexpected de exception\n",
    "    - Aceita como argumento um ponteiro para uma função sem nenhum argumento e um tipo de retorno void.\n",
    "    - Retorna um ponteiro para a última função chamada por unexpected.\n",
    "        - Retorna 0 na primeira vez.\n",
    "\n",
    "## 7 Processando exceções inesperadas (cont.)\n",
    "- Função terminate\n",
    "    - É chamada quando\n",
    "        - Não é encontrado nenhum catch correspondente à exceção lançada.\n",
    "        - Um destrutor tenta lançar uma exceção durante o desempilhamento.\n",
    "        - Há a tentativa de relançar uma exceção no momento em que nenhuma exceção está sento tratada.\n",
    "        - Se a função unexpected for chamada antes de registrar uma função com a função set_unexpected.\n",
    "    - Chama a função registrada com a função set_terminate.\n",
    "    - A função abort é chamada por padrão.\n",
    "\n",
    "## 7 Processando exceções inesperadas (cont.)\n",
    "- Função set_terminate\n",
    "    - Aceita como argumento um ponteiro para uma função sem nenhum argumento e um tipo de retorno void.\n",
    "    - Retorna um ponteiro para a última função chamada por terminate.\n",
    "        - Retorna 0 na primeira vez.\n",
    "- Função abort\n",
    "    - Termina o programa sem chamar destrutores para objetos de classe de armazenamento automático ou estático.\n",
    "        - Pode provocar vazamento de recurso.\n",
    "\n",
    "## 8 Desempilhamento de pilha\n",
    "- Desempilhamento\n",
    "    - Ocorre quando uma exceção lançada não é capturada em um determinado escopo.\n",
    "    - Desempilhar uma função encerra essa função.\n",
    "        - Todas as variáveis locais da função são destruídas.\n",
    "        - O controle retorna à instrução que invocou a função.\n",
    "    - São feitas tentativas de capturar a exceção em blocos try…catch externos.\n",
    "    - Se a exceção nunca for capturada, a função terminate será chamada.\n",
    "- Rode o programa **Fig16_04()** abaixo e observe o seu código fonte [Fig16_04.cpp](src/ch16/Fig16_04/Fig16_04.cpp).\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "function1 is called inside main\n",
      "function2 is called inside function1\n",
      "function3 is called inside function2\n",
      "In function 3\n",
      "Exception occurred: runtime_error in function3\n",
      "Exception handled in main\n"
     ]
    }
   ],
   "source": [
    "// Fig. 16.4: Fig16_04.cpp\n",
    "// Demonstrando o desempilhamento.\n",
    "#include \"src/ch16/Fig16_04/Fig16_04.cpp\"\n",
    "\n",
    "Fig16_04();"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9 Construtores, destrutores e tratamento de exceções\n",
    "- Exceções e construtores\n",
    "    - As exceções permitem que os construtores, que não podem retornar valores, informem erros ao programa.\n",
    "    - As exceções lançadas por construtores fazem com que qualquer objeto de componente já construído chame seus destrutores.\n",
    "        - Apenas os objetos que já tiverem sido construídos serão destruídos.\n",
    "- Exceções e destrutores\n",
    "    - Os destrutores são chamados para todos os objetos automáticos no bloco try encerrado quando uma exceção é lançada.\n",
    "        - Os recursos adquiridos podem ser colocados nos objetos locais a fim de liberá-los automaticamente no momento em que ocorrer uma exceção.\n",
    "    - Se um destrutor invocado por desempilhamento lançar uma exceção, a função terminate será chamada.\n",
    "\n",
    "## Dica de prevenção de erro 4\n",
    "- Quando uma exceção é lançada do construtor de um objeto que é criado em uma expressão new, a memória dinamicamente alocada desse objeto é liberada.\n",
    "\n",
    "## 10 Exceções e herança\n",
    "- Herança com classes de exceção\n",
    "    - Novas classes de exceção podem ser definidas para herdar de classes de exceção existentes.\n",
    "    - Um handler para captura para uma determinada classe de exceção também pode capturar exceções de classes derivadas dessa classe.\n",
    "\n",
    "## Dica de prevenção de erro 5\n",
    "- Utilizar herança com exceções permite criar um handler de exceção para capturar erros relacionados com a notação concisa. \n",
    "- Uma abordagem é capturar cada tipo de ponteiro ou referência para um objeto de exceção de classe derivada individualmente, \n",
    "    - mas uma abordagem mais concisa é capturar as referências ou ponteiros para objetos de exceção de classe básica. \n",
    "- Além disso, capturar ponteiros ou referências a objetos de exceção de classe derivada individualmente pode provocar erros, especialmente se o programador se esquecer de testar explicitamente um ou mais dos tipos de referência ou de ponteiros de classe derivada.\n",
    "\n",
    "## 11 Processando falhas new\n",
    "- Falhas new\n",
    "    - Alguns compiladores lançam uma exceção bad_alloc.\n",
    "        - Compatíveis com a especificação-padrão do C++.\n",
    "    - Alguns compiladores retornam 0.\n",
    "        - Os compiladores compatíveis com o padrão C++ também têm uma versão de new que retorna 0.\n",
    "            - Use a expressão new( nothrow ), onde nothrow é do tipo nothrow_t.\n",
    "    - Alguns compiladores lançam bad_alloc se o arquivo de cabeçalho new estiver incluído.\n",
    "\n",
    "- Rode os programas **Fig16_05()/Fig16_06()** abaixo e observe o seu código fonte [Fig16_05.cpp](src/ch16/Fig16_05/Fig16_05.cpp)/[Fig16_06.cpp](src/ch16/Fig16_06/Fig16_06.cpp)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Allocated 5000000000000 doubles in ptr[ 0 ]\n",
      "Allocated 5000000000000 doubles in ptr[ 1 ]\n",
      "Allocated 5000000000000 doubles in ptr[ 2 ]\n"
     ]
    },
    {
     "ename": "Standard Exception",
     "evalue": "std::bad_alloc",
     "output_type": "error",
     "traceback": [
      "Standard Exception: std::bad_alloc"
     ]
    }
   ],
   "source": [
    "// Fig. 16.5: Fig16_05.cpp\n",
    "// Demonstrando new pré-padrão retornando 0 quando a memória\n",
    "// não é alocada.\n",
    "#include \"src/ch16/Fig16_05/Fig16_05.cpp\"\n",
    "\n",
    "Fig16_05();"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Allocated 5000000000000 doubles in ptr[ 0 ]\n",
      "Allocated 5000000000000 doubles in ptr[ 1 ]\n",
      "Allocated 5000000000000 doubles in ptr[ 2 ]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception occurred: std::bad_alloc\n"
     ]
    }
   ],
   "source": [
    "// Fig. 16.6: Fig16_06.cpp\n",
    "// Demonstrando new padrão lançando bad_alloc quando a memória\n",
    "// não pode ser alocada.\n",
    "#include \"src/ch16/Fig16_06/Fig16_06.cpp\"\n",
    "\n",
    "Fig16_06();"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Observação de engenharia de software 8\n",
    "- Para tornar os programas mais robustos, utilize a versão de new que lança exceções bad_alloc em caso de falhas.\n",
    "\n",
    "## 11 Processando falhas new (cont.)\n",
    "- Falhas new (cont.)\n",
    "    - Função set_new_handler\n",
    "        - Registra uma função para tratar falhas new.\n",
    "            - A função registrada é chamada por new quando uma operação de alocação de memória falha.\n",
    "        - Aceita como argumento um ponteiro para uma função que não aceita nenhum argumento e retorna void.\n",
    "        - O C++ padrão especifica que a função handler de new deve:\n",
    "            - Disponibilizar mais memória e permitir que new tente novamente\n",
    "            - Lançar uma exceção bad_alloc ou\n",
    "            - Chamar a função abort ou exit para encerrar o programa.\n",
    "- Rode o programa **Fig16_07()** abaixo e observe o seu código fonte [Fig16_07.cpp](src/ch16/Fig16_07/Fig16_07.cpp)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Allocated 5000000000 doubles in ptr[ 0 ]\n",
      "Allocated 5000000000 doubles in ptr[ 1 ]\n",
      "Allocated 5000000000 doubles in ptr[ 2 ]\n",
      "Allocated 5000000000 doubles in ptr[ 3 ]\n",
      "Allocated 5000000000 doubles in ptr[ 4 ]\n",
      "Allocated 5000000000 doubles in ptr[ 5 ]\n",
      "Allocated 5000000000 doubles in ptr[ 6 ]\n",
      "Allocated 5000000000 doubles in ptr[ 7 ]\n",
      "Allocated 5000000000 doubles in ptr[ 8 ]\n",
      "Allocated 5000000000 doubles in ptr[ 9 ]\n",
      "Allocated 5000000000 doubles in ptr[ 10 ]\n",
      "Allocated 5000000000 doubles in ptr[ 11 ]\n",
      "Allocated 5000000000 doubles in ptr[ 12 ]\n",
      "Allocated 5000000000 doubles in ptr[ 13 ]\n",
      "Allocated 5000000000 doubles in ptr[ 14 ]\n",
      "Allocated 5000000000 doubles in ptr[ 15 ]\n",
      "Allocated 5000000000 doubles in ptr[ 16 ]\n",
      "Allocated 5000000000 doubles in ptr[ 17 ]\n",
      "Allocated 5000000000 doubles in ptr[ 18 ]\n",
      "Allocated 5000000000 doubles in ptr[ 19 ]\n",
      "Allocated 5000000000 doubles in ptr[ 20 ]\n",
      "Allocated 5000000000 doubles in ptr[ 21 ]\n",
      "Allocated 5000000000 doubles in ptr[ 22 ]\n",
      "Allocated 5000000000 doubles in ptr[ 23 ]\n",
      "Allocated 5000000000 doubles in ptr[ 24 ]\n",
      "Allocated 5000000000 doubles in ptr[ 25 ]\n",
      "Allocated 5000000000 doubles in ptr[ 26 ]\n",
      "Allocated 5000000000 doubles in ptr[ 27 ]\n",
      "Allocated 5000000000 doubles in ptr[ 28 ]\n",
      "Allocated 5000000000 doubles in ptr[ 29 ]\n",
      "Allocated 5000000000 doubles in ptr[ 30 ]\n",
      "Allocated 5000000000 doubles in ptr[ 31 ]\n",
      "Allocated 5000000000 doubles in ptr[ 32 ]\n",
      "Allocated 5000000000 doubles in ptr[ 33 ]\n",
      "Allocated 5000000000 doubles in ptr[ 34 ]\n",
      "Allocated 5000000000 doubles in ptr[ 35 ]\n",
      "Allocated 5000000000 doubles in ptr[ 36 ]\n",
      "Allocated 5000000000 doubles in ptr[ 37 ]\n",
      "Allocated 5000000000 doubles in ptr[ 38 ]\n",
      "Allocated 5000000000 doubles in ptr[ 39 ]\n",
      "Allocated 5000000000 doubles in ptr[ 40 ]\n",
      "Allocated 5000000000 doubles in ptr[ 41 ]\n",
      "Allocated 5000000000 doubles in ptr[ 42 ]\n",
      "Allocated 5000000000 doubles in ptr[ 43 ]\n",
      "Allocated 5000000000 doubles in ptr[ 44 ]\n",
      "Allocated 5000000000 doubles in ptr[ 45 ]\n",
      "Allocated 5000000000 doubles in ptr[ 46 ]\n",
      "Allocated 5000000000 doubles in ptr[ 47 ]\n",
      "Allocated 5000000000 doubles in ptr[ 48 ]\n",
      "Allocated 5000000000 doubles in ptr[ 49 ]\n"
     ]
    }
   ],
   "source": [
    "// Fig. 16.7: Fig16_07.cpp\n",
    "// Demonstrando set_new_handler.\n",
    "#include \"src/ch16/Fig16_07/Fig16_07.cpp\"\n",
    "\n",
    "Fig16_07();   "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12 Classe auto_ptr e alocação de memória dinâmica\n",
    "- Template de classe auto_ptr\n",
    "    - É definido no arquivo de cabeçalho memory.\n",
    "    - Mantém um ponteiro para alocar memória dinamicamente.\n",
    "        - Seu destrutor realiza uma operação delete no membro de dados do ponteiro.\n",
    "            - Isso evita vazamento de memória por meio da exclusão da memória alocada dinamicamente, mesmo se ocorrer uma exceção.\n",
    "        - Fornece os operadores sobrecarregados * e -> da mesma maneira que uma variável de ponteiro regular.\n",
    "        - Pode transferir a posse da memória por meio do operador de atribuição sobrecarregado ou do construtor de cópia.\n",
    "            - O último objeto auto_ptr que estiver mantendo o ponteiro realizará uma operação delete na memória.\n",
    "            \n",
    "- Classe Integer [Integer.h](src/ch16/Fig16_08_10/Integer.h)/[Integer.cpp](src/ch16/Fig16_08_10/Integer.cpp)\n",
    "- Rode o programa **Fig16_10()** abaixo e observe o seu código fonte [Fig16_10.cpp](src/ch16/Fig16_08_10/Fig16_10.cpp).\n",
    "        - Linha 18, Cria um auto_ptr para apontar para um objeto Integer dinamicamente alocado.\n",
    "        - Linha 21 e 24, Manipula auto_ptr como se fosse um ponteiro para um  Integer.\n",
    "        - Linha 25, A memória alocada dinamicamente é automaticamente excluída de auto_ptr quando ele sai do escopo.        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating an auto_ptr object that points to an Integer\n",
      "Constructor for Integer 7\n",
      "\n",
      "Using the auto_ptr to manipulate the Integer\n",
      "Integer after setInteger: 99Destructor for Integer 99\n"
     ]
    }
   ],
   "source": [
    "// Fig. 16.10: Fig16_10.cpp\n",
    "// Demonstrando auto_ptr.\n",
    "#include \"src/ch16/Fig16_08_10/Fig16_10.cpp\"\n",
    "\n",
    "Fig16_10();"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Observação de engenharia de software 9\n",
    "- Um auto_ptr tem restrições em certas operações. \n",
    "- Por exemplo:\n",
    "    - um auto_ptr não pode apontar para um array ou uma classe contêiner padrão.\n",
    "\n",
    "## 13 Hierarquia de exceções da biblioteca-padrão\n",
    "- Classes de hierarquia de exceções\n",
    "    - Classe básica exception\n",
    "        - Contém a função virtual what para o armazenamento de mensagens de erro.\n",
    "        - Classes de exceção derivadas de exception\n",
    "            - bad_alloc – lançada por new\n",
    "            - bad_cast – lançada por dynamic_cast\n",
    "            - bad_typeid – lançada por  typeid\n",
    "            - bad_exception – lançada por unexpected\n",
    "                - Em vez de encerrar o programa ou chamar a função especificada por set_unexpected\n",
    "                - Usada apenas se bad_exception estiver na lista throw da função.\n",
    "\n",
    "## Erro comum de programação 8\n",
    "- Colocar um handler catch que captura um objeto de classe básica antes de um catch que captura um objeto de uma classe derivada dessa classe básica é um erro de lógica. \n",
    "- A classe básica catch captura todos os objetos de classe derivada dessa classe básica. \n",
    "- Desse modo, a classe derivada catch nunca executará.\n",
    "\n",
    "## Classes de exceções da biblioteca-padrão.\n",
    "<img src=\"img/Picture136.png\" width=\"100%\" height=\"100%\">\n",
    "\n",
    "\n",
    "## 13 Hierarquia de exceções da biblioteca-padrão (cont.)\n",
    "- Classes de hierarquia de exceções (cont.)\n",
    "    - Classe logic_error, derivada de exception\n",
    "        - Indica erros na lógica do programa.\n",
    "        - Classes de exceção derivadas de logic_error\n",
    "            - invalid_argument\n",
    "                - Indica um argumento inválido para uma função.\n",
    "            - length_error\n",
    "                - Indica que foi utilizado um comprimento superior ao tamanho máximo usado para alguns objetos.\n",
    "            - out_of_range\n",
    "                - Indica que um valor, como um subscrito de array,  ultrapassou o intervalo permitido.\n",
    "\n",
    "## 13 Hierarquia de exceções da biblioteca-padrão (cont.)\n",
    "- Classes de hierarquia de exceções (cont.)\n",
    "    - Classe runtime_error, derivada de exception\n",
    "        - Indica erros de tempo de execução.\n",
    "        - Classes de exceção derivadas de runtime_error\n",
    "            - overflow_error\n",
    "                - Indica um erro de  overflow aritmético — um resultado aritmético é maior que o maior número armazenável.\n",
    "            - underflow_error\n",
    "                - Indica um erro de underflow aritmético — um resultado aritmético é menor que o menor número armazenável.\n",
    "\n",
    "## Erro comum de programação 9 \n",
    "- As classes de exceções definidas pelo programador não precisam ser derivadas da classe exception. \n",
    "- Portanto, escrever catch( exception anyException ) não garante a captura (catch) de todas as exceções que um programa poderia encontrar.\n",
    "\n",
    "## Dica de prevenção de erro 6\n",
    "- Para capturar todas as exceções potencialmente lançadas em um bloco try, utilize catch(...). \n",
    "- Um ponto fraco desse método de captura de exceções é que o tipo da exceção capturada é desconhecido em tempo de compilação. \n",
    "- Outro ponto fraco é que, sem um parâmetro identificado, não há nenhuma maneira de referenciar o objeto exceção dentro do handler de exceção.\n",
    "\n",
    "## Observação de engenharia de software 10\n",
    "- A hierarquia exception padrão é um bom ponto de partida para criar exceções. \n",
    "- Os programadores podem construir programas que podem \n",
    "    - lançar exceções-padrão, \n",
    "    - lançar exceções derivadas das exceções-padrão ou \n",
    "    - lançar suas próprias exceções não derivadas das exceções-padrão.\n",
    "\n",
    "## Observação de engenharia de software 11\n",
    "- Utilize catch(...) para realizar uma recuperação que não depende do tipo de exceção (por exemplo, liberar recursos comuns). \n",
    "- A exceção pode ser relançada para alertar handlers catch envolventes mais específicos.\n",
    "\n",
    "## 14 Outras técnicas de tratamento de erro\n",
    "- Outras técnicas de tratamento de erro\n",
    "    - Ignore a exceção\n",
    "        - Isso é devastador para softwares comerciais e de missão crítica.\n",
    "    - Aborte o programa\n",
    "        - Isso evita que um programa forneça resultados incorretos aos usuários.\n",
    "        - É inapropriado para aplicativos de missão crítica.\n",
    "        - Se conseguir um recurso, o programa deve liberá-lo antes da terminação do programa.\n",
    "    - Configure indicadores de erro\n",
    "        - Emita uma mensagem de erro e passe um código de erro apropriado por meio de exit ao ambiente do programa.\n",
    "\n",
    "## Erro comum de programação 10\n",
    "- Abortar um componente de programa em decorrência de uma exceção não interceptada poderia fazer com que um recurso — como um fluxo de arquivo ou um dispositivo de E/S — ficasse indisponível para outros programas. \n",
    "- Isso é conhecido como ‘vazamento de recurso’."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "C++14",
   "language": "C++14",
   "name": "xeus-cling-cpp14"
  },
  "language_info": {
   "codemirror_mode": "text/x-c++src",
   "file_extension": ".cpp",
   "mimetype": "text/x-c++src",
   "name": "c++",
   "version": "14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
